Areas/Admin/Controllers/CoverTypeController.cs
using BulkyBook.DataAccess;
using BulkyBook.DataAccess.Repository.IRepository;
using BulkyBook.Models;
using Microsoft.AspNetCore.Mvc;

namespace BulkyBookWeb.Controllers
{
    [Area("Admin")]
    public class CoverTypeController : Controller
    {
        private readonly IUnitOfWork _Db;
        public CoverTypeController(IUnitOfWork Db)
        {
            _Db = Db;
        }
        public IActionResult Index()
        {
            IEnumerable<CoverType> objCoverType = _Db.CoverType.GetAll();
            return View(objCoverType);
        }
        //Get
        public IActionResult Create()
        {
           
            return View();
        }
        //Post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(CoverType obj)
        {
            
            if (ModelState.IsValid)
            {
                _Db.CoverType.Add(obj);
                _Db.Save();
                TempData.Add("Success", "Create Successfully");
                return RedirectToAction("Index");
            }
           return View();
        }
        //Get
        public IActionResult Edit(int? id)
        {
            if (id== null || id ==0)
            {
                return NotFound();
            }
            var covertype = _Db.CoverType.GetFirstOrDefault(x=>x.Id==id);
            if (covertype == null)
            {
                return NotFound();
            }
            return View(covertype);
        }
        //Post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(CoverType obj)
        {
            
            if (ModelState.IsValid)
            {
                _Db.CoverType.Update(obj);
                _Db.Save();
                TempData.Add("Success", "Edit Successfully");
                return RedirectToAction("Index");
            }
            return View();
        }
        //Get
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var covertype = _Db.CoverType.GetFirstOrDefault(x => x.Id == id);
            if (covertype == null)
            {
                return NotFound();
            }
            return View(covertype);
        }
        //Post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteCoverType(int? id)
        {
            var covertype = _Db.CoverType.GetFirstOrDefault(x => x.Id == id);
            if (covertype != null)
            {
                _Db.CoverType.Remove(covertype);
                _Db.Save();
                TempData.Add("Success", "Delete Cover Type Successfully");
                return RedirectToAction("Index");
            }
            return View();
        }
    }
}

Areas/Admin/Controllers/ProductController.cs
using BulkyBook.DataAccess;
using BulkyBook.DataAccess.Repository.IRepository;
using BulkyBook.Models;
using BulkyBook.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace BulkyBookWeb.Controllers
{
    [Area("Admin")]
    public class ProductController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _hostEnvironment;
        public ProductController(IUnitOfWork Db, IWebHostEnvironment hostEnv)
        {
            _unitOfWork = Db;
            _hostEnvironment= hostEnv;
        }
        public IActionResult Index()
        {
            //IEnumerable<Product> objProduct = _unitOfWork.Product.GetAll();
            return View();
        }
       
        //Get
        public IActionResult Upsert(int? id)
        {
            ProductVM productVM= new()
            {
                product = new(),
                categories = _unitOfWork.Category.GetAll().Select(x=> new SelectListItem{
                    Text = x.Name,
                    Value = x.Id.ToString()
                }),
                covertypes = _unitOfWork.CoverType.GetAll().Select(x => new SelectListItem
                {
                    Text = x.Name,
                    Value = x.Id.ToString()
                })
            };
            if (id== null || id ==0)
            {
                
                return View(productVM);
            }
            else
            {
                productVM.product = _unitOfWork.Product.GetFirstOrDefault(x => x.Id == id);
                return View(productVM);
            }
            
           
        }
        //Post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(ProductVM obj, IFormFile? file)
        {
            
            if (ModelState.IsValid)
            {
                string wwwRootPath = _hostEnvironment.WebRootPath;
                if (file != null)
                {
                    string FileName = Guid.NewGuid().ToString();
                    var uploads = Path.Combine(wwwRootPath,@"images\products");
                    var extention = Path.GetExtension(file.FileName).ToLower();
                    if (obj.product.ImageUrl != null)
                    {
                        var oldimgpath = Path.Combine(wwwRootPath,obj.product.ImageUrl.TrimStart('\\'));
                        if (System.IO.File.Exists(oldimgpath))
                        {
                            System.IO.File.Delete(oldimgpath);
                        }
                    }
                    using (var fileStreams = new FileStream(Path.Combine(uploads,FileName+ extention),FileMode.Create))
                    {
                        file.CopyTo(fileStreams);
                    }
                    obj.product.ImageUrl = @"images\products" + FileName + extention;
                }
                if (obj.product.Id == 0)
                {
                    _unitOfWork.Product.Add(obj.product);
                }
                else
                {
                    _unitOfWork.Product.Update(obj.product);
                }
                _unitOfWork.Save();
                TempData.Add("Success", "Edit Successfully");
                return RedirectToAction("Index");
            }
            return View();
        }
        //Get
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var product = _unitOfWork.Product.GetFirstOrDefault(x => x.Id == id);
            if (product == null)
            {
                return NotFound();
            }
            return View(product);
        }
        //Post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteProduct(int? id)
        {
            var product = _unitOfWork.Product.GetFirstOrDefault(x => x.Id == id);
            if (product != null)
            {
                _unitOfWork.Product.Remove(product);
                _unitOfWork.Save();
                TempData.Add("Success", "Delete Product Successfully");
                return RedirectToAction("Index");
            }
            return View();
        }
        #region API Calls
        [HttpGet]
        public IActionResult GetAll()
        {
            var productList = _unitOfWork.Product.GetAll(includeProperties:"Category,CoverType");
            return Json(new { data = productList });
        }
        #endregion
    }
}

Controllers/CategoryController.cs
using BulkyBook.DataAccess;
using BulkyBook.Models;
using Microsoft.AspNetCore.Mvc;

namespace BulkyBookWeb.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ApplicationDBContext _Db;
        public CategoryController(ApplicationDBContext Db)
        {
            _Db = Db;
        }
        public IActionResult Index()
        {
            IEnumerable<Category> objCategory = _Db.Categories.ToList();
            return View(objCategory);
        }
        //Get
        public IActionResult Create()
        {
           
            return View();
        }
        //Post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Category obj)
        {
            if (_Db.Categories.FirstOrDefault(x=>x.DisplayOrder== obj.DisplayOrder) != null)
            {
                ModelState.AddModelError("DisplayOrder", "Display Order has been exist in list");
            }
            if (ModelState.IsValid)
            {
                _Db.Categories.Add(obj);
                _Db.SaveChanges();
                TempData.Add("Success", "Create Successfully");
                return RedirectToAction("Index");
            }
           return View();
        }
        //Get
        public IActionResult Edit(int? id)
        {
            if (id== null || id ==0)
            {
                return NotFound();
            }
            var category = _Db.Categories.Find(id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }
        //Post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Category obj)
        {
            
            if (ModelState.IsValid)
            {
                _Db.Categories.Update(obj);
                _Db.SaveChanges();
                TempData.Add("Success", "Edit Successfully");
                return RedirectToAction("Index");
            }
            return View();
        }
        //Get
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var category = _Db.Categories.Find(id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }
        //Post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteCategory(int? id)
        {
            var category = _Db.Categories.Find(id);
            if(category != null)
            {
                _Db.Categories.Remove(category);
                _Db.SaveChanges();
                TempData.Add("Success", "Delete Category Successfully");
                return RedirectToAction("Index");
            }
            return View();
        }
    }
}

Views/Shared/Notification.cshtml
@if(TempData["Success"] != null)
{ 
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["Success"]')
        </script>
}
@if(TempData["Error"] != null)
{
     <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
   <script type="text/javascript">
        toastr.error('@TempData["Error"]')
        </script>

}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BulkyBookWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/BootsWatchTheme.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BulkyBookWeb.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.0/font/bootstrap-icons.css">
    <link rel="stylesheet" href="//cdn.datatables.net/1.11.5/css/jquery.dataTables.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Bulky Boook</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarColor01">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">         
            <a class="nav-link" asp-area="Customer" asp-controller="Home" asp-action="Index">Home</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Content Management</a>
          <div class="dropdown-menu">
           <a class="dropdown-item" asp-area="Admin" asp-controller="Category" asp-action="Index">Category</a>
           <a class="dropdown-item" asp-area="Admin" asp-controller="CoverType" asp-action="Index">CoverType</a>
           <a class="dropdown-item" asp-area="Admin" asp-controller="Product" asp-action="Index">Product</a>
          </div>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-sm-2" type="text" placeholder="Search">
        <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
        @*<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BulkyBookWeb</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Category</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>*@
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="Notification"/>
            @RenderBody()
        </main>
    </div>

    <footer class="footer text-muted bg-primary">
        <div class="container">
            &copy; 2022 - BulkyBookWeb - <a asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="//cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>